/registerTicket.do=ticket.command.RegisterTicketHandler
/ticketList.do=ticket.command.ListTicketHandler
/parkInOut.do=park.command.ParkInOutHandler
/parkStatusList.do=park.command.ParkStatusListHandler